#######################################
# Hello-world service                 #
#######################################
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  ports:
  -  
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
      version: v1
  template:
    metadata:
      labels:
        app: hello-world
        version: v1
    spec:
      containers:
      - 
        name: hello-world
        image: mariogabrielg/hello-sentelis:latest
        imagePullPolicy: Always
        ports:
        - 
          containerPort: 8000
---
#######################################
# External Backend Service            #
#######################################
kind: Service
apiVersion: v1
metadata:
 name: external-service
Spec:
 type: ClusterIP
 ports:
 - 
   port: 80
   targetPort: 27017
---
kind: Endpoints
apiVersion: v1
metadata:
 name: external-service
subsets:
 - 
   addresses:
     - 
       ip: 10.240.0.4
   ports:
     - 
       port: 27017
---
#######################################
# Kong Route                          #
#######################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
spec:
  rules:
  - 
    http:
      paths:
      - 
        path: /hello
        backend:
          serviceName: hello-world
          servicePort: 80
      - 
        path: /backend
        backend:
          serviceName: external-service
          servicePort: 80
---