gateways:
  enabled: false

galley:
  enabled: false

mixer:
  policy:
    enabled: false
  telemetry:
    enabled: false

pilot:
  enabled: false

security:
  enabled: true
  createMeshPolicy: false

prometheus:
  enabled: false

sidecarInjectorWebhook.enabled: true


global:
  istioRemote: true

  defaultPodDisruptionBudget: {}

  enableTracing: false

  remotePilotAddress: 10.1.1.13

  remotePolicyAddress: 10.1.1.12

  remoteTelemetryAddress: 10.1.0.10

  remotePilotCreateSvcEndpoint: true


  # Sets an identifier for the remote network to be used for Split Horizon EDS. The network will be sent
  # to the Pilot when connected by the sidecar and will affect the results returned in EDS requests.
  # Based on the network identifier Pilot will return all local endpoints + endpoints of gateways to
  # other networks.
  #
  # Must match the names in the meshNetworks section in the Istio local.
  network: ""
